import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar  } from "@/components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body>
      <SidebarProvider>
        <div className="flex w-full h-screen bg-gray-200">
          <AppSidebar />
          <main className="flex-1 p-6 overflow-y-auto bg-gray-100">
          <SidebarTrigger />
            {children}
          </main>
          <Toaster />
        </div>
      </SidebarProvider>

      </body>
    </html>
  );
}

